### ISSUE TITLE
Build errors for different examples

### ISSUE THREAD

**Issue by ivankravets** [Infineon/platformio-infineonxmc#3]
Please take a look at https://travis-ci.org/Infineon/platformio-infineonxmc and fix examples.

Thanks!

**Comment by sherylll** [comment]
Hi Ivan, 

this is due to some bugs in the latest release of the XMC core, the current code in [master ](https://github.com/Infineon/XMC-for-Arduino)worked fine in previous builds.

I'll update travis as soon as a new release is made!

**Comment by sherylll** [comment]
Travis now passing

**Comment by ivankravets** [comment]
Please enable AppVeyor https://www.appveyor.com/ , we should also process tests on Windows

I added config a few days before.
