### ISSUE TITLE
Problem with the Variants of the XMC library

### ISSUE THREAD

**Issue by djaumann** [Infineon/platformio-infineonxmc#7]
I think there is a verison problem.
I'm working with the XMC4700 right now and I found out that the variants files are not up to date.

In my particular case I'm using the **XMC-for-Arduino/arm/variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h** and that part is missing:

```javascript

extern uint8_t SS; 
extern uint8_t MOSI;
extern uint8_t MISO;
extern uint8_t SCK;

```

I also tried to update my platform, but PIO is saying that everything is up to date.
Maybe you can take a look at that issue.

Thanks in advance.

Best Regards
Dominik

**Comment by sherylll** [comment]
Hi,
Can you check it out:
https://github.com/Infineon/platformio-infineonxmc/commit/d7f37973db2aaca34f16010463b8e6c960b03251

To use latest platformio script, configure your `platform.ini` file with the below option
```
[env:development]
platform = https://github.com/Infineon/platformio-infineonxmc.git
board = ...
...
```

Cheers,

**Comment by djaumann** [comment]
Hey sherylll,

I checked it out and it's working :)
Thank you very much for the quick fix.

Best Regards,
Domi
