### ISSUE TITLE
Porting from DAVE

### ISSUE THREAD

**Issue by Michael-F-Ellis** [Infineon/platformio-infineonxmc#8]
We have developed a custom board using the XMC4700 and DAVE.  It's part of a larger project involving other computers and languages.  The team would prefer to do all development with VSCode if possible.

I'm trying to assess what would need to be done to extract the source code we presently have in DAVE and build/debug it under VSCode.

Apologies if this isn't the right place to ask this question.

Thanks!

**Comment by ArkajyotiChatterjee** [comment]
Hello Michael,
Well Platform.IO(VS Code extension) for Infineon XMC4700 uses C++. And I guess DAVE project for you is in C.
As you can see, XMC4700 can be programmed from Arduino IDE or Platform.Io or DAVE.
So you need to port all your libraries and API and make it compliant with our XMC-for-Arduino API's.
Change the application layer (main.c and corresponding/related files) to resemble a .ino(for Arduino IDE) or Main.cpp (with Arduino libraries in Platform.IO).
I am sorry if it sounds a bit ambiguous or complicated but your question was also very vague.
I would be happy to help you if you add in some more details.
Regards,
Arka

**Comment by Michael-F-Ellis** [comment]
Thanks, Arka. I'm out of town this week.  Will coordinate with the other
member of the team next week to try be more specific about our project.
Cheers,
Mike

*“I want you to act as if the house was on fire. Because it is.” — Greta
Thunberg*

**Comment by ArkajyotiChatterjee** [comment]
Hello Michael,
Sure. It would be great if you can specify what peripherals of XMC are you using, what protocols are using and how your application layer looks like.
After I have those pieces of information, I can explain what you need to do to port to VS Code.
But one question: I have seen people from Arduino/VS Code environment moving to DAVE/Keil but not the other way around. So what prompted you and your team to move from DAVE to Arduino/VS Code environment.
Regards,
Arka
